- id: '6'
  alias: Notification Presence Detection - Entrance
  trigger:
  - entity_id: binary_sensor.door_window_sensor_entrance
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Main Entrance Door Opened
      title: Intruder Alert
    service: notify.notifyhumair
  - data:
      message: Main Entrance Door Opened
      title: Intruder Alert
    service: notify.notifytauseef
  - data:
      entity_id: script.webcam_snapshot
    service: homeassistant.turn_on
- id: '16'
  alias: Single Click to switch ON Living Room Lights
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d0001243b98
    event_type: click
    platform: event
  action:
  - data:
      brightness: '175'
      entity_id: light.dining_room
    service: light.turn_on
  - data:
      brightness: '255'
      entity_id: light.lounge
    service: light.turn_on
  - data:
      brightness: '60'
      entity_id: light.staircase
    service: light.turn_on
- id: '17'
  alias: Motion Gateway Light - ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_livingroom
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '300'
    condition: numeric_state
    entity_id: sensor.illumination_xiaomi
  - after: '22:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness: 255
      entity_id: light.gateway_light_7811dcdc2bae
      rgb_color:
      - 255
      - 255
      - 255
    service: light.turn_on
- id: '18'
  alias: Motion Gateway Light - OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_livingroom
    for:
      minutes: 5
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.gateway_light_7811dcdc2bae
    service: light.turn_off
- id: '1523705703675'
  alias: Double Click to switch OFF Living Room Lights
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d0001243b98
    event_type: click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.dining_room
    service: light.turn_off
  - data:
      entity_id: light.staircase
    service: light.turn_off
  - data:
      entity_id: light.lounge
    service: light.turn_off
- id: '1524098486581'
  alias: Exterior Lights ON at Sunset
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.exterior_lights
    service: switch.turn_on
- id: '1524098673901'
  alias: Exterior Lights Off on Sunrise
  trigger:
  - event: sunrise
    offset: -01:00:00
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.exterior_lights
    service: switch.turn_off
- action:
  - service: ifttt.trigger
    data:
      event: TestHA_trigger
      value1: Hello World!
  alias: Startup Notification
  id: '99999'
  trigger:
    platform: homeassistant
    event: start
- action:
  - service: ifttt.trigger
    data:
      event: Xiaomi_Unavailable
      value1: Xiaomi is unavailable
  alias: Notify when Xiaomi Unavailable
  condition: []
  id: '1525613592545'
  trigger:
  - entity_id: light.gateway_light_7811dcdc2bae
    platform: state
    to: unavailable
- id: '1526853874400'
  alias: Notify when Xiaomi Available
  trigger:
  - entity_id: light.gateway_light_7811dcdc2bae
    platform: state
    to: available
  condition: []
  action:
  - data:
      event: Xiaomi_Available
      value1: Xiaomi is Available now
    service: ifttt.trigger
- id: '1528855480276'
  alias: Humair - Notify Presence - Left Office
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: Left Work
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Left Office
      title: Humair
- id: '1528855480376'
  alias: Humair - Notify Presence - At Home
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: At Home
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Arrived Home
      title: Humair
- id: '1528855480476'
  alias: Humair - Notify Presence - At Office
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: At Work
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Arrived at Office
      title: Humair
- id: '1528855480576'
  alias: Tauseef - Notify Presence - Arrived Home
  trigger:
  - entity_id: sensor.tauseef_presence
    platform: state
    to: At Home
  condition: []
  action:
  - service: notify.notifyhumair
    data:
      message: Arrived Home
      title: Tauseef
- id: '1528855480676'
  alias: Tauseef - Notify Presence - Left Home
  trigger:
  - entity_id: sensor.tauseef_presence
    platform: state
    to: Left Home
  condition: []
  action:
  - service: notify.notifyhumair
    data:
      message: Left Home
      title: Tauseef
- id: '1533444272995'
  alias: Test
  trigger:
  - platform: template
    value_template: '{{ now().time().strftime("%H:%M") == states.sensor.maghrib_azan_time.state
      }}'
  condition: []
  action:
  - data:
      entity_id: media_player.mibox3
      media_content_id: https://www.youtube.com/watch?v=tPXAB5sQMs0
      media_content_type: best
    service: media_extractor.play_media
- id: '1534616461690'
  alias: Hydro Consumption Notification 1
  trigger:
  - at: '15:00'
    platform: time
  condition:
  - condition: template
    value_template: '{{ states.sensor.hydroquebec_period_total_bill.state| float >
      80 }}'
  action:
  - data_template:
      message: Consumption is {{ states.sensor.hydroquebec_period_total_bill.state|
        float }} for {{ states.sensor.hydroquebec_period_length.state | float }} days
      title: Hydro Consumption
    service: notify.notifyhumair
  - data_template:
      message: Consumption is {{ states.sensor.hydroquebec_period_total_bill.state|
        float }} for {{ states.sensor.hydroquebec_period_length.state| float }} days
      title: Hydro Consumption
    service: notify.notifytauseef
- id: '1535874317727'
  alias: Motion Staircase Light - ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_stairs
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '30'
    condition: numeric_state
    entity_id: sensor.illumination_stairs
  - after: '20:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness: 10
      entity_id: light.staircase
    service: light.turn_on
- id: '1535874769635'
  alias: Motion Staircase Light - OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_stairs
    for:
      minutes: 1
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '20:00'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: light.staircase
    service: light.turn_off
- id: '1535940084179'
  alias: Motion Bedroom1 Light - ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_bedroom1
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '20:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness: 1
      entity_id: light.bedroom1
    service: light.turn_on
- id: '1535940578685'
  alias: Motion Bedroom1 Light - OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_bedroom1
    for:
      minutes: 1
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '21:00'
    before: 06:00
    condition: time
  action:
  - data:
      entity_id: light.bedroom1
    service: light.turn_off
- id: '1536894450619'
  alias: Motion Bedroom1 Light - ON (day)
  trigger:
  - entity_id: binary_sensor.motion_sensor_bedroom1
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '30'
    condition: numeric_state
    entity_id: sensor.illumination_bedroom1
  - after: 06:00
    before: '20:00'
    condition: time
  action:
  - data:
      brightness: 255
      entity_id: light.bedroom1
    service: light.turn_on
- id: '1542750904651'
  alias: Humair - Notify Presence - At Train Station
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: At Train Station
  condition: []
  action:
  - data:
      message: Arrived at Train Station
      title: Humair
    service: notify.notifytauseef
- id: '1542750989465'
  alias: Humair - Notify Presence - Left Train Station
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: Left Train Station
  condition: []
  action:
  - data:
      message: Leaving Train Station
      title: Humair
    service: notify.notifytauseef
