- alias: Telegram Bot - Take Webcam Snapshots
  id: '1'
  trigger:
  - event_data:
      command: /picture
    event_type: telegram_command
    platform: event
  action:
  - data:
      brightness: '255'
      entity_id: light.color_lamp_2
    service: light.turn_on
  - delay: 0:0:5
  - data:
      entity_id: script.webcam_snapshot
    service: homeassistant.turn_on
  - delay: 0:0:5
  - data:
      data:
        photo:
        - caption: Living Room Picture
          url: http://mediaserver/image.jpg
      message: Living Room Picture
      title: Intruder Alert
    service: notify.notifyhumair
  - delay: 0:0:5
  - data:
      entity_id: script.archive_webcam_snapshot
    service: homeassistant.turn_on
- action:
  - data:
      data:
        keyboard:
        - /picture, /video
      message: Movement Detected in Room3
      title: Intruder Alert
    service: notify.notifyhumair
  - data:
      brightness: '255'
      entity_id: light.color_lamp_3
    service: light.turn_on
  alias: Presence Detection - Room 3
  condition: []
  id: '1513112861399'
  trigger:
  - entity_id: sensor.pir_sensor__room3
    platform: state
    to: '1'
- id: '4007'
  alias: Telegram Bot - Welcom Message
  hide_entity: true
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /start
  action:
  - service: notify.notifyhumair
    data_template:
      title: Welcome to Zeda
      message: What shall we do today?
      data:
        keyboard:
        - /picture, /video
- action:
  - data:
      brightness: '255'
      entity_id: light.color_lamp_1
    service: light.turn_on
  - data:
      brightness: '255'
      entity_id: light.color_lamp_2
    service: light.turn_on
  - data:
      brightness: '255'
      entity_id: light.white_lamp_1
    service: light.turn_on
  alias: Presence Detection - Living Room
  condition: []
  id: '1513168004359'
  trigger:
  - entity_id: sensor.pir_sensor__livingroom
    platform: state
    to: '1'
- action:
  - data:
      data:
        keyboard:
        - /picture, /video
      message: Movement Detected in Living Room
      title: Intruder Alert
    service: notify.notifyhumair
  - data:
      entity_id: script.webcam_snapshot
    service: homeassistant.turn_on
  alias: Notification Presence Detection - Living Room
  condition: []
  id: '1513193210740'
  trigger:
  - entity_id: sensor.pir_sensor__livingroom
    platform: state
    to: '1'
- action:
  - data:
      entity_id: light.color_lamp_1
    service: light.turn_off
  - data:
      entity_id: light.color_lamp_2
    service: light.turn_off
  - data:
      entity_id: light.white_lamp_1
    service: light.turn_off
  alias: No Presenece Detection - Living Room
  condition: []
  id: '1513193442182'
  trigger:
  - entity_id: sensor.pir_sensor__livingroom
    platform: state
    to: '0'
- alias: Take Webcam video
  id: '1111111222333'
  trigger:
  - event_data:
      command: /video
    event_type: telegram_command
    platform: event
  action:
  - data:
      entity_id: script.webcam_video
    service: homeassistant.turn_on
  - data:
      message: Video Recording
      title: Please wait
    service: notify.notifyhumair
  - data:
      brightness: '255'
      entity_id: light.color_lamp_2
    service: light.turn_on
  condition:
  - condition: state
    entity_id: sensor.is_video_running
    state: 'off'
- action:
  - data:
      data:
        keyboard:
        - /picture, /video
      message: Movement Detected on Entrance
      title: Intruder Alert
    service: notify.notifyhumair
  alias: Notification Presence Detection - Entrance
  condition: []
  id: '8888193210740'
  trigger:
  - entity_id: sensor.pir_sensor__entrance
    platform: state
    to: '1'
- action:
  - data:
      entity_id: light.color_lamp_3
    service: light.turn_off
  alias: No Presence Detection - Room 3
  condition: []
  id: '1513251327721'
  trigger:
  - entity_id: sensor.pir_sensor__room3
    platform: state
    to: '0'
- action:
  - data:
      data:
        video:
        - caption: video of living room
          url: http://mediaserver/video.mp4
      message: Video of Living Room
      title: Intruder Alert
    service: notify.notifyhumair
  - data:
      entity_id: light.color_lamp_2
    service: light.turn_off
  - data:
      entity_id: script.archive_webcam_snapshot
    service: homeassistant.turn_on
  alias: Send Video
  condition: []
  id: '1513267002615'
  trigger:
  - entity_id: sensor.is_video_running
    platform: state
    to: 'off'
- action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  alias: If All Away
  condition: []
  id: '1513267551615'
  trigger:
  - entity_id: sensor.presence_all
    platform: state
    to: 'False'
