- id: '6'
  alias: Notification Presence Detection - Entrance
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002278850
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Main Entrance Door Opened
      title: Intruder Alert
    service: notify.notifyhumair
  - data:
      message: Main Entrance Door Opened
      title: Intruder Alert
    service: notify.notifytauseef
  - data:
      entity_id: script.webcam_snapshot
    service: homeassistant.turn_on
- id: '16'
  alias: Single Click to switch ON Living Room Lights
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d0001243b98
    event_type: click
    platform: event
  action:
  - data:
      brightness: '175'
      entity_id: light.dinning_room
    service: light.turn_on
  - data:
      brightness: '255'
      entity_id: light.living_room
    service: light.turn_on
  - data:
      brightness: '60'
      entity_id: light.staircase
    service: light.turn_on
- id: '17'
  alias: If there is motion and its dark turn on the gateway light
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001f46e9e
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '300'
    condition: numeric_state
    entity_id: sensor.illumination_7811dcdc2bae
  - after: '21:00'
    before: 06:00
    condition: time
  action:
  - data:
      brightness: 255
      entity_id: light.gateway_light_7811dcdc2bae
      rgb_color:
      - 255
      - 255
      - 255
    service: light.turn_on
  - data:
      brightness: 100
      entity_id: light.staircase
    service: light.turn_on
- id: '18'
  alias: If there no motion for 5 minutes turn off the gateway light
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d0001f46e9e
    for:
      minutes: 5
    from: 'on'
    platform: state
    to: 'off'
  action:
  - data:
      entity_id: light.gateway_light_7811dcdc2bae
    service: light.turn_off
  - data:
      entity_id: light.staircase
    service: light.turn_off
- id: '1523705703675'
  alias: Double Click to switch OFF Living Room Lights
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d0001243b98
    event_type: click
    platform: event
  condition: []
  action:
  - data:
      entity_id: light.dinning_room
    service: light.turn_off
  - data:
      entity_id: light.staircase
    service: light.turn_off
  - data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1524098486581'
  alias: Exterior Lights ON at Sunset
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.exterior_lights
    service: switch.turn_on
- id: '1524098673901'
  alias: Exterior Lights Off on Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      entity_id: switch.exterior_lights
    service: switch.turn_off
- action:
  - service: ifttt.trigger
    data:
      event: TestHA_trigger
      value1: Hello World!
  alias: Startup Notification
  id: '99999'
  trigger:
    platform: homeassistant
    event: start
- action:
  - service: ifttt.trigger
    data:
      event: Xiaomi_Unavailable
      value1: Xiaomi is unavailable
  alias: Notify when Xiaomi Unavailable
  condition: []
  id: '1525613592545'
  trigger:
  - entity_id: light.gateway_light_7811dcdc2bae
    platform: state
    to: unavailable
- id: '1526853874400'
  alias: Notify when Xiaomi Available
  trigger:
  - entity_id: light.gateway_light_7811dcdc2bae
    platform: state
    to: available
  condition: []
  action:
  - data:
      event: Xiaomi_Available
      value1: Xiaomi is Available now
    service: ifttt.trigger
- id: '1528855480276'
  alias: Humair - Notify Presence - Left Office
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: Left Work
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Left Office
      title: Humair
- id: '1528855480376'
  alias: Humair - Notify Presence - At Home
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: At Home
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Arrived Home
      title: Humair
- id: '1528855480476'
  alias: Humair - Notify Presence - At Office
  trigger:
  - entity_id: sensor.humair_presence
    platform: state
    to: At Work
  condition: []
  action:
  - service: notify.notifytauseef
    data:
      message: Arrived at Office
      title: Humair
- id: '1528855480576'
  alias: Tauseef - Notify Presence - Arrived Home
  trigger:
  - entity_id: sensor.tauseef_presence
    platform: state
    to: At Home
  condition: []
  action:
  - service: notify.notifyhumair
    data:
      message: Arrived Home
      title: Tauseef
- id: '1528855480676'
  alias: Tauseef - Notify Presence - Left Home
  trigger:
  - entity_id: sensor.tauseef_presence
    platform: state
    to: Left Home
  condition: []
  action:
  - service: notify.notifyhumair
    data:
      message: Left Home
      title: Tauseef
- id: '1533444272995'
  alias: Test
  trigger:
    platform: template
    value_template: '{{ now.time().strftime("%H:%M") == states.maghrib_azan_time.state }}'
  condition: []
  action:
  - data:
      entity_id: media_player.mibox3
      media_content_id: https://www.youtube.com/watch?v=tPXAB5sQMs0
      media_content_type: best
    service: media_extractor.play_media
