homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: !secret http_base_url
  trusted_networks:
     - 127.0.0.1
     - ::1
     - 192.168.2.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:


# View all events in a logbook
logbook:

# Track the sun
sun:

media_player:
  - platform: kodi
    host: 192.168.2.25
    port: 8080
    name: OSMC
  - platform: samsungtv
    host: 192.168.2.72 
  - platform: mpd
    host: homeserver
    
    
# Text to speech
tts:
  - platform: google

google_assistant:
 project_id: !secret google_project_id
 client_id: !secret google_client_id
 access_token: !secret google_access_token
 api_key: !secret google_api_key
 exposed_domains:
   - switch
   - light
   - group
 entity_config:
   switch.kitchen:
     name: kitchen
     aliases:
       - bright lights
       - entry lights
     type: light
   light.living_room:
     expose: false
     room: living room


mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password 

  
telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatID_Humair
    - !secret telegram_chatID_Tauseef 
    
notify:
  - platform: ios
  - name: notifyHumair
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Humair
  - name: notifyTauseef
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Tauseef
    
  
shell_command:
  take_snapshot_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/take_snapshot_webcam.sh'
  check_snapshot_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_snapshot_webcam.sh'
  copy_snapshot_webcam: 'scp osmc@mediaserver:/var/www/html/image.jpg /tmp/image.jpg'
  archive_snapshot_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/archive_snapshot_webcam.sh'
  take_video_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/take_video_webcam.sh'
  check_video_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_video_webcam.sh'
  archive_video_webcam: 'ssh osmc@mediaserver bash /home/osmc/humair/scripts/archive_video_webcam.sh'

device_tracker:
  - platform: owntracks

switch:
  - platform: mqtt
    name: alarm
    command_topic: "home/alarm/state"

#camera:
#  - platform: local_file
#    file_path: /tmp/image.jpg
#    name: Living Room
camera:
  name: Humair
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.owntrack_humair.attributes.latitude }},{{ states.device_tracker.owntrack_humair.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:SMH%7C{{ states.device_tracker.owntrack_humair.attributes.latitude }},{{ states.device_tracker.owntrack_humair.attributes.longitude }}
  limit_refetch_to_url_change: true

#Xiomi Gateway
xiaomi_aqara:
  gateways:
    - mac: !secret xiomi_gw_mac
      key: !secret xiomi_gw_key

group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
automation: !include automations.yaml
history: !include history.yaml
