- platform: hydroquebec
  username: !secret hydroquebec_username
  password: !secret hydroquebec_password
  contract: !secret hydroquebec_contract
  monitored_variables:
   - period_total_bill
   - period_length
   - period_total_days
   - period_lower_price_consumption
   - period_higher_price_consumption
   - yesterday_total_consumption
   - yesterday_lower_price_consumption
   - yesterday_higher_price_consumption 
- platform: mqtt
  name: humair_presence
  state_topic: "home/presence/humair"
- platform: mqtt
  name: tauseef_presence
  state_topic: "home/presence/tauseef"
# - platform: mqtt
  # state_topic: "home/room3/pir/state"
  # name: "pir sensor @ room3"
# - platform: mqtt
  # state_topic: "home/livingroom/pir/state"
  # name: "pir sensor @ livingroom"
# - platform: mqtt
  # state_topic: "home/entrance/pir/state"
  # name: "pir sensor @ entrance"
# - platform: mqtt
  # state_topic: "home/entrance/lightintensity/value"
  # name: "light sensor @ entrance"
# - platform: yr
# - platform: command_line
  # name: Is Video Running
  # command: "ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_video_webcam.sh"
  # scan_interval: 5
# - platform: command_line
  # name: Is Image Ready
  # command: "ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_snapshot_webcam.sh"
  # scan_interval: 5
- platform: template
  sensors:
    presence_all:
      value_template: "{{ states.media_player.samsung_tv_remote == 'on' or states.binary_sensor.motion_sensor_158d0001f46e9e.state == 'on' or states.binary_sensor.door_window_sensor_158d0002278850.state == 'on' or states.binary_sensor.motion_sensor_158d0001a9235d.state == 'on' or states.binary_sensor.motion_sensor_158d0001aeb665.state == 'on' or states.binary_sensor.door_window_sensor_158d0001bf4ca9.state == 'on' or states.binary_sensor.door_window_sensor_158d000200a8cd.state == 'on'}}"
      entity_id:
        - binary_sensor.motion_sensor_158d0001f46e9e
        - media_player.samsung_tv_remote
        - binary_sensor.door_window_sensor_158d0002278850
        - binary_sensor.motion_sensor_158d0001a9235d
        - binary_sensor.motion_sensor_158d0001aeb665
        - binary_sensor.door_window_sensor_158d0001bf4ca9
        - binary_sensor.door_window_sensor_158d000200a8cd
- platform: template
  sensors:
    main_door_sensor_bat:
      friendly_name: Xiaomi Main Door Sensor
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0002278850', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d0002278850.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: > 
        {% set battery_level_xod1 = states.binary_sensor.door_window_sensor_158d0002278850.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.door_window_sensor_158d0002278850', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    entrance_motion_sensor_bat:
      friendly_name: Xiaomi Entrance Motion Sensor
      value_template: >
        {% if is_state('binary_sensor.motion_sensor_158d0001f46e9e', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d0001f46e9e.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: > 
        {% set battery_level_xod1 = states.binary_sensor.motion_sensor_158d0001f46e9e.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.motion_sensor_158d0001f46e9e', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    button_1_bat:
      friendly_name: Xiaomi Button 1
      value_template: >
        {% if is_state('binary_sensor.switch_158d0001243b98', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.switch_158d0001243b98.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: > 
        {% set battery_level_xod1 = states.binary_sensor.switch_158d0001243b98.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.switch_158d0001243b98', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    entrance_motion_sensor_bat:
      friendly_name: Xiaomi Entrance Motion Sensor
      value_template: >
        {% if is_state('binary_sensor.motion_sensor_158d0001a9235d', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d0001a9235d.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.motion_sensor_158d0001a9235d.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.motion_sensor_158d0001a9235d', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    garage_motion_sensor_bat:
      friendly_name: Xiaomi Garage Motion Sensor
      value_template: >
        {% if is_state('binary_sensor.motion_sensor_158d0001aeb665', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d0001aeb665.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.motion_sensor_158d0001aeb665.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.motion_sensor_158d0001aeb665', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    garage_door_sensor_bat:
      friendly_name: Xiaomi Garage Entrace Door
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d0001bf4ca9', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d0001bf4ca9.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.door_window_sensor_158d0001bf4ca9.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.door_window_sensor_158d0001bf4ca9', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
- platform: template
  sensors:
    patio_door_sensor_bat:
      friendly_name: Xiaomi Patio Exit Door
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d000200a8cd', 'unknown') %}
          110
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d000200a8cd.attributes["battery_level"] | float}}
        {% endif %}
      icon_template: >
        {% set battery_level_xod1 = states.binary_sensor.door_window_sensor_158d000200a8cd.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('binary_sensor.door_window_sensor_158d000200a8cd', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
      unit_of_measurement: '%'
