# - platform: mqtt
  # state_topic: "home/room3/pir/state"
  # name: "pir sensor @ room3"
# - platform: mqtt
  # state_topic: "home/livingroom/pir/state"
  # name: "pir sensor @ livingroom"
# - platform: mqtt
  # state_topic: "home/entrance/pir/state"
  # name: "pir sensor @ entrance"
# - platform: mqtt
  # state_topic: "home/entrance/lightintensity/value"
  # name: "light sensor @ entrance"
# - platform: yr
# - platform: command_line
  # name: Is Video Running
  # command: "ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_video_webcam.sh"
  # scan_interval: 5
# - platform: command_line
  # name: Is Image Ready
  # command: "ssh osmc@mediaserver bash /home/osmc/humair/scripts/check_snapshot_webcam.sh"
  # scan_interval: 5
- platform: template
  sensors:
    presence_all:
      value_template: "{{ states.media_player.samsung_tv_remote == 'on' or states.binary_sensor.motion_sensor_158d0001f46e9e.state == 'on'}}"
      entity_id:
        - binary_sensor.motion_sensor_158d0001f46e9e
        - media_player.samsung_tv_remote
